spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.jpa.generate.ddl=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

spring.flyway.enabled=false

##'=update' just update all changes
##'=create' means db will be delete and create again folowing by entitie files. 
##'=validate' it will check correction of present DB
spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.http.converter=DEBUG

#Security and Authentication
jwt.token.secretKey = bMckU93tLqBfvyxHySw4SWOZ8ZmXOt5egCyTo/P6ni0=
#(60 000 mlsec = 1 min)
jwt.token.expired = 3600000

