import {
  REGISTER_SUCCESS,
  REGISTER_FAILED,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT_SUCCESS,
  LOGOUT_FAILED,
  LOADING,
  STOP_LOADING,
  CLEAR_LOGIN_STATE,
} from '../redux/actions/loginActions'
