name: CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            if [ "${{ github.ref_name }}" = "main" ]; then
              echo "Deploying production..."

              cd ~/WebApp-PcStore-Backend

              git pull --ff-only origin main

              docker compose \
                -f docker-compose.oracle.yml \
                up -d --build

            elif [ "${{ github.ref_name }}" = "dev" ]; then
              echo "Deploying development..."

              cd ~/WebApp-PcStore-Backend-dev

              git pull --ff-only origin dev

              docker compose \
                -p pcstore-dev \
                --env-file .env.dev \
                -f docker-compose.oracle.yml \
                up -d --build
            fi 
