name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Oracle
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd ~/WebApp-PcStore-Backend
            
            echo "Current branch:"
            git branch --show-current
            
            echo "Pulling main:"
            git pull origin main
            
            echo "Rebuilding and restarting application:"
            docker compose -f docker-compose.oracle.yml up -d --build