name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build backend image
        run: docker build -t pcstore-backend ./backend

      - name: Build frontend image
        run: docker build -t pcstore-frontend ./frontend